[package]
name = "fs-sam-software"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
quick-protobuf = "0.8.0"
spidev = "0.5.1"
fs-protobuf-rust = { path = "fs-protobuf-rust" }
